# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    jobs:
      - job:
        steps:
        - script: cd Project
          displayName: 'Go inside the Project directory'
          
        - task: Maven@4
          inputs:
            mavenPomFile: 'Project/pom.xml'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: true

        - script: sudo mvn package
          displayName: 'Execute the build of the project'
