# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    jobs:
      - job:
        steps:
        - script: cd Project
          displayName: 'Go inside the Project directory'
          
        - task: Maven@4
          inputs:
            mavenPomFile: 'Project/pom.xml'
            publishJUnitResults: true
            testRunTitle: 'Project/src/test/java/CalculatorTest.java'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

        #- script: mvn package
        #  displayName: 'Execute the build of the project'
        
        - script: pwd
          displayName: 'Check current directory'
          
        - script: ls
          displayName: 'Show files in the current directory'
